# -*- coding: utf-8 -*-
"""Correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FAt-muu8ckOV9GsboUTceFHrq90z97td
"""



import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/mydrive')



WQ_Data = pd.read_csv("/content/mydrive/MyDrive/Independent_variables_main.csv")

WQ_Data

WQ_Data[["HIV_2018", "HIV_2019", "HIV_2020", "HIV_2021", "HIV_2022", "HIV_POP", "TOT_HIV", "Prevalence_rate",]]

WQ_Data = WQ_Data.iloc[1:25, 9:26]

WQ_Data

CorrilationMatrix = WQ_Data.corr()
top_corr_features = CorrilationMatrix.index
plt.figure(figsize=(15,9))
g=sns.heatmap(WQ_Data[top_corr_features].corr(),annot=True,cmap="GnBu")

sns. set (font_scale=1)
plt.gcf () .set_size_inches (15, 9)
g.set_xticklabels (g.get_xmajorticklabels(), fontsize = 15)
g. set_yticklabels (g.get_ymajorticklabels(), fontsize = 15)
plt.title ('Correlation Matrix of Independent Variables', fontsize  = 15)
g=sns.heatmap(WQ_Data[top_corr_features].corr(),annot=True,cmap="GnBu")
plt.gcf () .set_size_inches (15, 9)